"""
Build layer1_db/typo_guard_words.txt — the list of REAL words that Layer 1's
typo corrector must never "fix".

Layer 1 corrects misspellings toward the database vocabulary ("myslef" ->
"myself", "suicde" -> "suicide", "kil" -> "kill"). A token that is itself an
ordinary English word must be left alone ("fill" is not a typo of "kill",
"skill" is not "kill"). Only real words within correction distance of a
database word can ever be at risk, so this file lists exactly those (plus
teen slang that is not in a dictionary) and ships with the repo. That makes
correction behave identically on every host — production servers usually have
no /usr/share/dict/words.

"Real word" means reasonably common English (wordfreq Zipf frequency >= 3.0,
roughly the 40k most-used words incl. inflections like "tried"). Obscure
dictionary entries ("neer", "sef", "wih") are NOT protected — in a student's
message those are typos. Word frequencies come from the free `wordfreq` package
(code Apache-2.0, data CC BY-SA 4.0, https://github.com/rspeer/wordfreq); it is
only needed to REBUILD this file, never at runtime.

It also writes layer1_db/common_words.txt (the ~600 most frequent words),
which are never rewritten even when the neighbouring words would spell a
database phrase.

Re-run after editing layer1_db/*.json:
    pip install wordfreq
    python3 build_typo_guard.py
"""
from __future__ import annotations

from pathlib import Path

import layer1

OUT = Path(__file__).resolve().parent / "layer1_db" / "typo_guard_words.txt"
# The most common English words are never rewritten even when neighbouring
# words would spell a database phrase ("i gave up soda" is not "i give up").
COMMON_OUT = Path(__file__).resolve().parent / "layer1_db" / "common_words.txt"
COMMON_N = 600

# Slang / chat words that are not in a dictionary but are not typos either.
SLANG_KEEP = """
lol lmao lmfao lmaoo rofl kmsl jk ngl fr tbh idk ik ikr smh bruh bro sus rn tmrw
omg omfg wtf wth ty thx pls plz lowkey highkey deadass finna gonna wanna gotta
imma ima tryna ain't aint yall y'all fam goat goated mid bussin cap nocap slay
periodt bestie rizz delulu yeet vibe vibes vibing ong frfr istg hbu wyd wbu hmu
ttyl brb gg ez nvm irl ofc stfu af asf lil fyp pov ate cooked crashout bet
""".split()


def _deletes(w: str, n: int) -> set:
    out = {w}
    frontier = {w}
    for _ in range(n):
        nxt = set()
        for x in frontier:
            for i in range(len(x)):
                nxt.add(x[:i] + x[i + 1:])
        out |= nxt
        frontier = nxt
    return out


MIN_ZIPF = 3.0


def _real_words() -> set:
    from wordfreq import top_n_list, zipf_frequency
    return {w for w in top_n_list("en", 200000)
            if w.isalpha() and w.isascii() and len(w) >= 3 and zipf_frequency(w, "en") >= MIN_ZIPF}


def main() -> None:
    words = _real_words()
    vocab = layer1._TYPO_VOCAB
    index: dict = {}
    for v in vocab:
        for d in _deletes(v, 2 if len(v) >= 7 else 1):
            index.setdefault(d, set()).add(v)
    keep = set()
    for w in words:
        if w in vocab:
            continue
        sq = layer1._squeeze(w)
        if sq in layer1._SQUEEZED_VOCAB:
            keep.add(w); continue
        for d in _deletes(w, 2):
            for v in index.get(d, ()):
                if layer1._dl(w, v) <= layer1._typo_budget(v):
                    keep.add(w); break
            else:
                continue
            break
    keep |= set(SLANG_KEEP)
    OUT.write_text("# generated by build_typo_guard.py — real words the typo corrector must not change\n"
                   "# (common English words near a database word, filtered with wordfreq, data CC BY-SA 4.0)\n"
                   + "\n".join(sorted(keep)) + "\n")
    print(f"{len(keep)} guard words -> {OUT}")
    from wordfreq import top_n_list
    common = sorted({w for w in top_n_list("en", COMMON_N) if w.isalpha() and w.isascii() and len(w) >= 3})
    COMMON_OUT.write_text("# generated by build_typo_guard.py — the most common English words; never\n"
                          "# context-corrected (wordfreq data CC BY-SA 4.0)\n" + "\n".join(common) + "\n")
    print(f"{len(common)} common words -> {COMMON_OUT}")


if __name__ == "__main__":
    main()
